let card1 = Card(c : Color.Spade, v : Value.Ace)
print(card1)
let card2 = Card(c : Color.Diamond, v: Value.Two)
print(card2)
print(card1 == card2)
print(card1 == card1)
print(card1.isEqual(card2))
print(card2.isEqual(card2))
print(card2.isEqual(55))