var deck1 = Deck.init(mixed: false)
var deck2 = Deck.init(mixed: true)
print(deck1)
print(deck2)
print("")
var card1 = deck1.draw()!
print(card1)
var card2 = deck2.draw()!
print(card2)
print("")
print(deck1)
print(deck2)
print("")
print(deck1.outs)
print(deck2.outs)
print("")
print(deck1.discards)
print(deck2.discards)
print("")
deck1.fold(c: deck1.outs[0])
deck2.fold(c: deck2.outs[0])
print("")
print(deck1.outs)
print(deck2.outs)
print("")
print(deck1.discards)
print(deck2.discards)
print("")
deck1.fold(c: card1)
deck2.fold(c: card2)
print("")
print(deck1.outs)
print(deck2.outs)
print("")
print(deck1.discards)
print(deck2.discards)